[platformio]
default_envs = esp32dev
src_dir = firmware/src
include_dir = firmware/include

[env:esp32dev]
platform = https://github.com/pioarduino/platform-espressif32/releases/download/55.03.311/platform-espressif32.zip
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -D DEFENSELAB_ENABLE_OLED=0
lib_deps =
  olikraus/U8g2@^2.36.12
