[platformio]
default_envs = esp32dev

[env:esp32dev]
platform = espressif32 @ 6.12.0
board = esp32dev
framework = arduino
monitor_speed = 115200
build_flags =
  -DDEFENSELAB_OLED=0

[env:esp32dev_oled]
extends = env:esp32dev
build_flags =
  -DDEFENSELAB_OLED=1
lib_deps =
  olikraus/U8g2 @ ^2.36.12
